version: "3"
services:
  qbittorrent-eta-bot:
    build: .
    container_name: qbittorrent-eta-bot
    environment:
      DISCORD_TOKEN: "your_discord_bot_token"
      QB_URL: "http://<qbittorrent-server>:8080"
      QB_USERNAME: "your_qbittorrent_username"
      QB_PASSWORD: "your_qbittorrent_password"
    restart: unless-stopped
